image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -R demo-files public
    - cp demo.html public
    - cp style.css public
  artifacts:
    paths:
        - public
  only:
    - master
